package myproject;



import javax.swing.*;
import java.sql.*;





/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */




/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {
Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
   
    public Main() {
       
        initComponents();  
       
     

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jOptionPane1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scrollbar1 = new java.awt.Scrollbar();
        jScrollPane4 = new javax.swing.JScrollPane();
        boldButton = new javax.swing.JButton();
        boldButton2 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane6 = new javax.swing.JScrollPane();
        notesField = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        boldButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseDragged(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        boldButton.setText("BOLD");
        boldButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boldButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boldButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boldButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boldButtonMouseReleased(evt);
            }
        });

        boldButton2.setText("BOLD");
        boldButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boldButton2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boldButton2MouseReleased(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));

        jScrollPane2.setViewportView(jScrollBar1);

        jScrollPane6.setViewportView(notesField);

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME    TO   TAVNOTES");

        jButton1.setText("SAVE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton3.setText("ITALIC");

        jButton4.setText("UNDERLINE");

        logoutButton.setText("LOGOUT");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });

        clearButton.setText("CLEAR");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        jButton7.setText("PREVIOUS NOTES");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        boldButton3.setText("BOLD");
        boldButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boldButton3MouseClicked(evt);
            }
        });
        boldButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boldButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(clearButton)
                            .addComponent(jButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(408, 408, 408)
                                .addComponent(boldButton3)
                                .addGap(49, 49, 49)
                                .addComponent(jButton3)
                                .addGap(38, 38, 38)
                                .addComponent(jButton4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(logoutButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(352, 352, 352)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(boldButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 130, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(94, 94, 94)
                                .addComponent(clearButton)
                                .addGap(71, 71, 71)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutButton)
                                .addGap(80, 80, 80))))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseDragged
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jScrollPane1MouseDragged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
     try (Connection con = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/tavrince_notes", "root", "123456")) {

    String newText = notesField.getText().trim();

    if (newText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Notes cannot be empty!");
        return;
    }
     
    // FIRST: GET EXISTING NOTES
    String selectSQL = "SELECT notes FROM notes WHERE Id = ?";
    PreparedStatement selectPst = con.prepareStatement(selectSQL);
    selectPst.setInt(1, Session.loggedInUserId);

    ResultSet rs = selectPst.executeQuery();
    String existingNotes = "";

    if (rs.next()) {
        existingNotes = rs.getString("notes");
    }

    rs.close();
    selectPst.close();

    // APPEND NEW NOTES TO OLD NOTES
    String updatedNotes = existingNotes + "\n" + newText;

    // UPDATE NOTES
    String updateSQL = "UPDATE notes SET notes = ? WHERE Id = ?";
    PreparedStatement updatePst = con.prepareStatement(updateSQL);
    updatePst.setString(1, updatedNotes);
    updatePst.setInt(2, Session.loggedInUserId);

    int rowUpdated = updatePst.executeUpdate();
    updatePst.close();

    if (rowUpdated > 0) {
        JOptionPane.showMessageDialog(this, "Your note has been added!");
        this.setVisible(false);
        new Main().setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "No notes found for this account.");
    }

} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
}


        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        getBalanceFromDatabase();
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
      new loginToMyProject().setVisible(true);
        this.setVisible(false);    
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        // TODO add your handling code here:
        notesField.setText("");
    }//GEN-LAST:event_clearButtonMouseClicked

    private void boldButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boldButtonMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_boldButtonMouseClicked

    private void boldButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boldButtonMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_boldButtonMouseExited

    private void boldButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boldButtonMousePressed
        // TODO add your handling code here:
 
        
    }//GEN-LAST:event_boldButtonMousePressed

    private void boldButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boldButtonMouseReleased
        // TODO add your handling code here:
     
    }//GEN-LAST:event_boldButtonMouseReleased

    private void boldButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boldButton2MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_boldButton2MouseClicked

    private void boldButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boldButton2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_boldButton2MouseReleased

    private void boldButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boldButton3ActionPerformed
        // TODO add your handling code here:
         makeEditorPaneTextBold(notesField);
    }//GEN-LAST:event_boldButton3ActionPerformed

    private void boldButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boldButton3MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_boldButton3MouseClicked

    private void getBalanceFromDatabase() {
   
    String sql = "SELECT notes FROM notes WHERE Id = ?";

    try (Connection con = DriverManager.getConnection(
             "jdbc:mysql://localhost:3306/tavrince_notes", "root", "123456");
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setInt(1, Session.loggedInUserId);

        try (ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                String notes = rs.getString("notes");
                notesField.setText(notes);
            } else {
                JOptionPane.showMessageDialog(null, "Notes not found");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error fetching balance: " + e.getMessage());
    }
}
    
    public void makeEditorPaneTextBold(JEditorPane editorPane) {
    editorPane.setContentType("text/html");
    editorPane.setText("<html><b>" + editorPane.getText() + "</b></html>");
}
        public void undoBold(JEditorPane editorPane) {
    String text = editorPane.getText();

    // remove bold tags
    text = text.replace("<b>", "").replace("</b>", "");

    editorPane.setText(text);
}



    
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boldButton;
    private javax.swing.JToggleButton boldButton2;
    private javax.swing.JButton boldButton3;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton logoutButton;
    private javax.swing.JEditorPane notesField;
    private java.awt.Scrollbar scrollbar1;
    // End of variables declaration//GEN-END:variables
}
